export { assertTransition, canTransition, jobStates, type JobState } from './job-state.js';
export {
  isSensitiveQueryName,
  redactSensitiveText,
  redactSensitiveUrl,
  sensitiveQueryNames,
} from './redaction.js';
export {
  compressedTextureFamilyForExtension,
  isRuntimeCapabilities,
  runtimeCapabilitiesFromProbe,
  webGLCompressedTextureFamilies,
  type RuntimeCapabilities,
  type WebGLCompressedTextureFamily,
  type WebGLRuntimeCapabilities,
} from './runtime-capabilities.js';
export {
  knownNonessentialTelemetryRoutes,
  knownNonessentialTelemetryPathPrefixes,
  knownNonessentialTelemetryPathnames,
  knownTrackingDomainSuffixes,
  isKnownNonessentialEmbedUrl,
  isKnownNonessentialExternalUrl,
  isKnownNonessentialTelemetryUrl,
  isKnownTrackingUrl,
} from './tracking.js';
export {
  isNativeHandshakeRequest,
  isNativeHandshakeResult,
  isNativeHostErrorResponse,
  isNativeHostResponse,
  isNativeJobActionRequest,
  isNativeJobActionResult,
  isNativeMirrorCancelRequest,
  isNativeMirrorCancelResult,
  isNativeMirrorCreateRequest,
  isNativeMirrorProgressEvent,
  isNativeMirrorResult,
  isNativePostHandshakeRequest,
  isNativeResourceBodyChunkRequest,
  isNativeResourceBodyEndRequest,
  isNativeResourceBodyRequest,
  isNativeResourceBodyResult,
  isNativeResourceBodyStartRequest,
  nativeCaptureCompletionReasons,
  nativeHostErrorCodes,
  nativeJobActions,
  nativeMessagingCapabilities,
  nativeMessagingMaxMessageBytes,
  nativeMessagingProtocolVersion,
  nativeResourceBodiesMaxBytes,
  nativeResourceBodiesMaxCount,
  nativeResourceBodyChunkBytes,
  nativeResourceBodyMaxBytes,
  nativeResourceBodyStages,
  type NativeHandshakeRequest,
  type NativeHandshakeResult,
  type NativeHostErrorCode,
  type NativeHostErrorDetail,
  type NativeHostErrorResponse,
  type NativeHostRequest,
  type NativeHostResponse,
  type NativeCaptureCompletionReason,
  type NativeJobAction,
  type NativeJobActionRequest,
  type NativeJobActionResult,
  type NativeMirrorCancelRequest,
  type NativeMirrorCancelResult,
  type NativeMirrorCaptureInput,
  type NativeMirrorCreateRequest,
  type NativeMirrorProgressEvent,
  type NativeMirrorResourceInput,
  type NativeMirrorResult,
  type NativeMirrorResultStatus,
  type NativeMirrorResultSummary,
  type NativePostHandshakeRequest,
  type NativeResourceBodyChunkRequest,
  type NativeResourceBodyEndRequest,
  type NativeResourceBodyRequest,
  type NativeResourceBodyResult,
  type NativeResourceBodyStage,
  type NativeResourceBodyStartRequest,
} from './native-messaging.js';

export const protocolVersion = 2;
